ruby:
  file_extension: rb
  command: ruby code.rb test_cases.txt
cpp:
  file_extension: cpp
  command: g++ code.cpp && ./a.out < test_cases.txt
go:
  file_extension: go
  command: go run code.go < test_cases.txt
